#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  mouse_follows_focus on \
  focus_follows_mouse autofocus \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 06 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

~/.config/yabai/restore_spaces.py
~/.config/yabai/restore_displays.py

yabai -m rule --add 'app=^IntelliJ IDEA$' space=code
yabai -m rule --add 'app=^Code$' space=code

yabai -m rule --add 'app=^Obsidian$' space=org
yabai -m rule --add 'title=.* notes$' space=org

yabai -m rule --add 'app=^wezterm-gui$' space=terminal
yabai -m rule --add 'app=^iTerm2$' space=terminal

yabai -m rule --add 'app=^GatherV2$' space=misc

yabai -m rule --add 'app=^Google Chrome$' space=web
yabai -m rule --add 'app=^Gmail$' space=mail
yabai -m rule --add 'app=^Google Calendar$' space=calendar
yabai -m rule --add 'app=^Slack$' space=chat

yabai -m rule --add 'app=^choose$' manage=off
yabai -m rule --add app="^System Preferences$" manage=off

yabai -m rule --apply

#yabai -m signal --add event=display_added action="~/.config/yabai/restore_displays.py"
#yabai -m signal --add event=display_removed action="~/.config/yabai/restore_displays.py"
yabai -m signal --add event=system_woke action="~/.config/yabai/restore_spaces.py"

echo "yabai configuration loaded.."
